name: Update maw-muter.ahk

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for updates
        id: check-updates
        run: |
          current_hash=$(sha256sum maw-muter.ahk | awk '{print $1}')
          remote_hash=$(curl -sL https://raw.githubusercontent.com/tfurci/maw-muter/main/maw-muter_AHK/maw-muter.ahk | sha256sum | awk '{print $1}')
          if [ "$current_hash" != "$remote_hash" ]; then
            echo "Updating maw-muter.ahk..."
            cd MuteActiveWindow-Simple
            curl -sLO https://raw.githubusercontent.com/tfurci/maw-muter/main/maw-muter_AHK/maw-muter.ahk
            git config user.email "github-actions@github.com"
            git config user.name "GitHub Actions"
            git add maw-muter.ahk
            git commit -m "Update maw-muter.ahk"
            git push origin main
          else
            echo "No update available for maw-muter.ahk"
          fi
